#pragma once

const char BUY[] = "B";
const char SELL[] = "S";

//Commands
const char COMMAND_CREATE_ORDER[] = "CreateOrder";
const char COMMAND_CREATE_OCO[] = "CreateOCO";
const char COMMAND_CREATE_OTO[] = "CreateOTO";
const char COMMAND_JOIN_TO_NEW_CONTINGENCY_GROUP[] = "JoinToNewContingencyGroup";
const char COMMAND_JOIN_TO_EXISTING_CONTINGENCY_GROUP[] = "JoinToExistingContingencyGroup";
const char COMMAND_REMOVE_FROM_CONTINGENCY_GROUP[] = "RemoveFromContingencyGroup";
const char COMMAND_EDIT_ORDER[] = "EditOrder";
const char COMMAND_DELETE_ORDER[] = "DeleteOrder";
const char COMMAND_SET_SUBSCRIPTION_STATUS[] = "SetSubscriptionStatus";
const char COMMAND_UPDATE_MARGIN_REQUIREMENTS[] = "UpdateMarginRequirements";

//Order types

const char ORDER_TYPE_TRUE_MARKET_OPEN[] = "OM";
const char ORDER_TYPE_MARKET_OPEN[] = "O";
const char ORDER_TYPE_MARKET_OPEN_RANGE[] = "OR";
const char ORDER_TYPE_TRUE_MARKET_CLOSE[] = "CM";
const char ORDER_TYPE_MARKET_CLOSE[] = "C";
const char ORDER_TYPE_MARKET_CLOSE_RANGE[] = "CR";
const char ORDER_TYPE_STOP_ENTRY[] = "SE";
const char ORDER_TYPE_LIMIT_ENTRY[] = "LE";
const char ORDER_TYPE_ENTRY[] = "E";
const char ORDER_TYPE_STOP[] = "S";
const char ORDER_TYPE_LIMIT[] = "L";
const char ORDER_TYPE_LIMIT_OPEN[] = "OL";
const char ORDER_TYPE_LIMIT_CLOSE[] = "CL";

//TIF

const char TIF_GTC[] = "GTC";
const char TIF_IOC[] = "IOC";
const char TIF_DAY[] = "DAY";
const char TIF_FOK[] = "FOK";

//Peg

const char PEG_FROM_OPEN[] = "O";
const char PEG_FROM_CLOSE[] = "M";

//Subscription statuses

const char SUBSCRIPTION_STATUS_TRADABLE[] = "T";
const char SUBSCRIPTION_STATUS_DISABLE[] = "D";
const char SUBSCRIPTION_STATUS_VIEW_ONLY[] = "V";

//SystemProperties

const char SYSTEM_PROPERTY_BASE_CRNCY[] = "BASE_CRNCY";
const char SYSTEM_PROPERTY_BASE_UNIT_SIZE[] = "BASE_UNIT_SIZE";
const char SYSTEM_PROPERTY_BASE_CRNCY_PRECISION[] = "BASE_CRNCY_PRECISION";
const char SYSTEM_PROPERTY_BASE_CRNCY_SYMBOL[] = "BASE_CRNCY_SYMBOL";
const char SYSTEM_PROPERTY_BASE_TIME_ZONE[] = "BASE_TIME_ZONE";
const char SYSTEM_PROPERTY_COND_DIST[] = "COND_DIST";
const char SYSTEM_PROPERTY_COND_DIST_ENTRY[] = "COND_DIST_ENTRY";
const char SYSTEM_PROPERTY_END_TRADING_DAY[] = "END_TRADING_DAY";
const char SYSTEM_PROPERTY_FORCE_PASSWORD_CHANGE[] = "FORCE_PASSWORD_CHANGE";
const char SYSTEM_PROPERTY_MARKET_OPEN[] = "MARKET_OPEN";
const char SYSTEM_PROPERTY_QUERYDEPTH_0[] = "QUERYDEPTH_0";
const char SYSTEM_PROPERTY_QUERYDEPTH_1[] = "QUERYDEPTH_1";
const char SYSTEM_PROPERTY_QUERYDEPTH_2[] = "QUERYDEPTH_2";
const char SYSTEM_PROPERTY_QUERYDEPTH_3[]= "QUERYDEPTH_3";
const char SYSTEM_PROPERTY_QUERYDEPTH_4[] = "QUERYDEPTH_4";
const char SYSTEM_PROPERTY_QUERYDEPTH_5[] = "QUERYDEPTH_5";
const char SYSTEM_PROPERTY_QUERYDEPTH_6[] = "QUERYDEPTH_6";
const char SYSTEM_PROPERTY_QUERYDEPTH_7[] = "QUERYDEPTH_7";
const char SYSTEM_PROPERTY_QUERYDEPTH_8[] = "QUERYDEPTH_8";
const char SYSTEM_PROPERTY_QUERYDEPTH_h2[] = "QUERYDEPTH_h2";
const char SYSTEM_PROPERTY_QUERYDEPTH_h3[] = "QUERYDEPTH_h3";
const char SYSTEM_PROPERTY_QUERYDEPTH_h4[] = "QUERYDEPTH_h4";
const char SYSTEM_PROPERTY_QUERYDEPTH_h6[] = "QUERYDEPTH_h6";
const char SYSTEM_PROPERTY_QUERYDEPTH_h8[] = "QUERYDEPTH_h8";
const char SYSTEM_PROPERTY_SERVER_TIME_UTC[] = "SERVER_TIME_UTC";
const char SYSTEM_PROPERTY_SUPPORT_TICK_VOLUME[] = "SupportTickVolume";
const char SYSTEM_PROPERTY_TP_170[] = "TP_170";
const char SYSTEM_PROPERTY_TP_171[] = "TP_171";
const char SYSTEM_PROPERTY_TP_172[] = "TP_172";
const char SYSTEM_PROPERTY_TP_86[] = "TP_86";
const char SYSTEM_PROPERTY_TP_88[] = "TP_88";
const char SYSTEM_PROPERTY_TP_89[] = "TP_89";
const char SYSTEM_PROPERTY_TP_94[] = "TP_94";
const char SYSTEM_PROPERTY_CP_170[] = "CP_170";
const char SYSTEM_PROPERTY_CP_171[] = "CP_171";
const char SYSTEM_PROPERTY_CP_172[] = "CP_172";
const char SYSTEM_PROPERTY_CP_86[] = "CP_86";
const char SYSTEM_PROPERTY_CP_88[] = "CP_88";
const char SYSTEM_PROPERTY_CP_89[] = "CP_89";
const char SYSTEM_PROPERTY_CP_94[] = "CP_94";
const char SYSTEM_PROPERTY_TRAILING_DYNAMIC[] = "TRAILING_DYNAMIC";
const char SYSTEM_PROPERTY_TRAILING_FLUCTUATE[] = "TRAILING_FLUCTUATE";
const char SYSTEM_PROPERTY_TRAILING_FLUCTUATE_PTS_MAX[] = "TRAILING_FLUCTUATE_PTS_MAX";
const char SYSTEM_PROPERTY_TRAILING_FLUCTUATE_PTS_MIN[] = "TRAILING_FLUCTUATE_PTS_MIN";
const char SYSTEM_PROPERTY_PEGGED_STOP_LIMIT_DISABLED[] = "PEGGED_STOP_LIMIT_DISABLED";


